Feature/criando classe formulario de compras
DFaccio/bff-marketplace-aplicacao-app pull request #4
Opened 2023-10-09 01:16 UTC by DFaccio

2023-10-15 19:23 UTC, fysabelah requested changes

2023-10-15 19:23 UTC, fysabelah commented on pom.xml
>  			<artifactId>spring-boot-starter-actuator</artifactId>
Não entendi o significado do groupId. O que seria dducl?

2023-10-15 19:23 UTC, fysabelah commented on pom.xml
> -		</dependency>
Na tag description também pode remover o MVP

2023-10-15 19:23 UTC, fysabelah commented on pom.xml
> -		<dependency>
Percebi que temos muitas dependências... Estas já estão contando as que utilizaremos no futuro, certo?

2023-10-15 19:23 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceaplicacaoapp/Controller/FormularioDeCompraController.java
> +    private static final String LISTAR_PRODUTOS = "/listarProdutos";
Acho que o GET já seria listar. Então, o que acha de alterar esse nome de rota?

2023-10-15 19:23 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceaplicacaoapp/Controller/FormularioDeCompraController.java
>  @RestController
Acho que seria interessante adicionar uma rota base para este controller. Algo como formulario, por exemplo.

Bastaria adicionar a tag @RequestMapping(value = "formulario")

2023-10-15 19:23 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceaplicacaoapp/ServiceImpl/FormularioDeCompraServiceImpl.java
> +        return (FormularioDeCompraListDTO) formularioLista;
Acho que ao invés de utilizar cast. Seria melhor criar classe conversoras.

- Vou criar uma tarefa a parte para isso.

2023-10-15 19:23 UTC, fysabelah commented on pom.xml
> -			<groupId>org.springframework.boot</groupId>
Favor, remover versionamento do .mvn, mvnw e mvnw.cmd

2023-10-15 19:23 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceaplicacaoapp/DTO/FormularioDeCompraDTO.java
> +    private String conteudoProduto;
O projeto possui lombok em sua dependência. Favor, remover get e set que não façam algum tipo de manipulação especifica e adicionar as anotações @Getter e @Setter.

2023-10-15 19:23 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceaplicacaoapp/Controller/FormularioDeCompraController.java
> +        return (List<FormularioDeCompraDTO>) formularioService.consultarProdutos();
Remover cast. Fazer uso de conversores.

- Caso não queira fazer isso agora, criei tarefa para isso

2023-10-15 19:23 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceaplicacaoapp/DTO/FormularioDeCompraListDTO.java
>  public class FormularioDeCompraListDTO {
Essa classe não deve existir. Deve haver uma classe de conversão entre FormularioDeCompra e FormularioDeCompra e ela pode receber e retonar uma lista.

2023-10-15 19:23 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceaplicacaoapp/ServiceImpl/FormularioDeCompraServiceImpl.java
> +    public FormularioDeCompraListDTO consultarProdutos(){
Método consultar deve permitir filtros por data, produto, quantidade, etc.

2023-10-15 19:23 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceaplicacaoapp/Controller/FormularioDeCompraController.java
> +    private String LISTAR_PRODUTOS = "listarProdutos";
Por mim, não acho que há necessidade disto ser uma variável, até porque dever ser utilizada em apenas um lugar. Porém, caso prefira que seja uma, favor adicionar static final.

2023-10-15 19:23 UTC, fysabelah commented on pom.xml
>  	<name>bff-marketplace-aplicacao-app</name>
O que seria o bff? Seria possível deixar apenas o aplicacao ou app?

2023-10-15 19:23 UTC, fysabelah commented on pom.xml
>  	<groupId>br.com.dducl</groupId>
Qual seria o significado de dducl?

2023-10-15 19:23 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceaplicacaoapp/DTO/FormularioDeCompraDTO.java
> +    }
Como nenhum get e set é especifico, todos podem ser alterados pelas anotações @Getter e @Setter do lombok

2023-10-15 22:04 UTC, DFaccio commented on pom.xml
>  	<groupId>br.com.dducl</groupId>
dducl é o Diário De Um Coffe Lover :)

2023-10-15 22:05 UTC, DFaccio commented on pom.xml
>  	<name>bff-marketplace-aplicacao-app</name>
bbf é o Backend For Frontend
termo usado onde eu trabalho

2023-10-15 22:06 UTC, DFaccio commented on pom.xml
> -		</dependency>
alterado para "Sistema para um marketplace de compra coletiva de cafe"

2023-10-15 22:07 UTC, DFaccio commented on pom.xml
> -		<dependency>
seria por isso mesmo, mas eu removi algumas

2023-10-15 22:13 UTC, DFaccio commented on src/main/java/br/com/dducl/bffmarketplaceaplicacaoapp/DTO/FormularioDeCompraDTO.java
> +    private String conteudoProduto;
podemos usar o lombok sim
foi mais pra exercitar a declaração dos getters e setters

2023-10-15 22:15 UTC, DFaccio commented on src/main/java/br/com/dducl/bffmarketplaceaplicacaoapp/ServiceImpl/FormularioDeCompraServiceImpl.java
> +    public FormularioDeCompraListDTO consultarProdutos(){
como a ideia agora era apenas devolver algo no postman, pensei em criar a lista no **for** abaixo.
mas podemos criar algum filtro sim, se for factível no tempo que temos

2023-10-17 00:38 UTC, erickmatheusribeiro commented on pom.xml
>  			<artifactId>spring-boot-starter-actuator</artifactId>
@fysabelah, receio que seu questionamento já tenha sido respondido aqui https://github.com/DFaccio/bff-marketplace-aplicacao-app/pull/4/files#r1359957986

2023-10-17 00:42 UTC, erickmatheusribeiro commented on pom.xml
> -		<dependency>
Tenho receio de estarmos "inflando" muito o projeto nessa etapa, talvez seja interessante colocarmos somente as dependências que iremos utilizar nessa fase.

2023-10-17 02:12 UTC, DFaccio commented on src/main/java/br/com/dducl/bffmarketplaceaplicacaoapp/Controller/FormularioDeCompraController.java
>  @RestController
Sim, eu estava com esse pensamento também

2023-10-20 22:34 UTC, closed without merging