Feature/cria classes portfolio
DFaccio/bff-marketplace-aplicacao-app pull request #44
Opened 2023-10-31 04:03 UTC by DFaccio

2023-10-31 12:24 UTC, fysabelah requested changes

2023-10-31 12:24 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceapp/dto/PortfolioDto.java
> +    private Integer id;
Dto possui id. Então poderia utilizar o de lá mesmo

2023-10-31 12:24 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceapp/modelo/entidades/Portfolio.java
> +    private List<Produto> portfolioProdutos;
deixaria o nome como produtos. Ele já pertence a classe portifolio. Não repetiria o portifolio no nome

2023-10-31 12:24 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceapp/controller/PortfolioController.java
> +    @DeleteMapping("/delete/{id}")
Será possível deletar um portifólio? Suponhamos que tenhamos uma compra relacionada ao portifólio, se ele for deletado será perdido este registro

2023-10-31 12:24 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceapp/modelo/entidades/Portfolio.java
>      @Temporal(TemporalType.TIMESTAMP)
Não há problemas em deixar, mas fiz um teste e vi que funciona sem a anotação column devido as outras anotações

2023-10-31 12:24 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceapp/modelo/persistencia/PortfolioRepository.java
> +    Optional<Portfolio> findByDescricaoEqualsIgnoreCase(String descricao);
Para descrição acho interessante ser like e não equals. Se não será obrigado saber a descrição completa. Aí daria para retornar uma lista e não apenas um

2023-10-31 12:24 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceapp/modelo/entidades/Portfolio.java
> +    @Column
Esse atributo tem que ser adicionado a arquitetura. O mesmo não existe

2023-10-31 12:24 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceapp/negocio/PortfolioBusiness.java
> +        Optional<Fornecedor> fornecedor = fornecedorRepository.findFornecedorByPessoaIdentificador(dto.getFornecedor().getInformacoes().getIdentificador());
Se utilizar a camada de negócio, essa parte de validação de fornecedor já foi resolvido por lá

2023-10-31 12:24 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceapp/negocio/PortfolioBusiness.java
> +        if (portfolioCriado.isPresent()) {
Pelo visto descrição é nome do portifólio, certo? Se for, talvez seja interessante mudar o nome do atributo

2023-10-31 12:24 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceapp/negocio/PortfolioBusiness.java
> +        if (fornecedor.isPresent()){
Aqui acho que é melhor validar se está vazio. Caso sim lança a exceção. Caso não segue atribuindo. Isso remove o if-else

2023-10-31 12:24 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceapp/negocio/PortfolioBusiness.java
> +        if (portfolio.isEmpty()) {
Tem uma classe que valida não encontrado. É a NotFound alguma coisa. A mensagem também já é manipulado por lá

2023-10-31 12:24 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceapp/negocio/PortfolioBusiness.java
> +        if (portfolioDeletar.isEmpty()){
Aqui também poderia utilizar a classe NotFoundException (acho que esse é  o nome)

2023-10-31 12:24 UTC, fysabelah commented on src/main/java/br/com/dducl/bffmarketplaceapp/negocio/PortfolioBusiness.java
> +        return "Portfólio deletado com sucesso!";
Aqui ao invés de retornar o feedback pode ser feito no próprio controller. Então aqui retorna void. Lá, se não der exception ele manda essa mensagem

2023-10-31 16:35 UTC, AydanAmorim commented on src/main/java/br/com/dducl/bffmarketplaceapp/controller/PortfolioController.java
> +    @DeleteMapping("/delete/{id}")
Ótimo ponto!

mas me recordo de um caso, eu acho que daria um erro.
Eu sei que se e eu tentar excluir um produto, o postgree não permite pois existe dependencias em outras tabelas, neste caso não daria uma exception também?

2023-10-31 16:39 UTC, AydanAmorim commented on src/main/java/br/com/dducl/bffmarketplaceapp/modelo/persistencia/PortfolioRepository.java
> +    Optional<Portfolio> findByDescricaoEqualsIgnoreCase(String descricao);
Podemos discutir isto, eu peguei uma situação ao fazer um teste usando o like.

1° Cadastrei um portfolio com a descrição: "Portfólio de Café Natal 2023";
2° eu tentei cadastrar "Porfólio de Café Natal" somente, e o like me dá que o registro já existia;

Não sei se este caso vai ocorrer na prática kkkk

2023-10-31 16:40 UTC, AydanAmorim commented on src/main/java/br/com/dducl/bffmarketplaceapp/negocio/PortfolioBusiness.java
> +        if (portfolioCriado.isPresent()) {
Faz todo o sentido, posso mudar o atributo para "nome", de acordo?

2023-10-31 23:52 UTC, AydanAmorim commented on src/main/java/br/com/dducl/bffmarketplaceapp/dto/PortfolioDto.java
> +    private Integer id;
Ok - alterado!

2023-10-31 23:53 UTC, AydanAmorim commented on src/main/java/br/com/dducl/bffmarketplaceapp/modelo/entidades/Portfolio.java
> +    private List<Produto> portfolioProdutos;
Ok - alterado!

2023-10-31 23:53 UTC, AydanAmorim commented on src/main/java/br/com/dducl/bffmarketplaceapp/modelo/entidades/Portfolio.java
>      @Temporal(TemporalType.TIMESTAMP)
Ok - Não alterado.

2023-10-31 23:59 UTC, AydanAmorim commented on src/main/java/br/com/dducl/bffmarketplaceapp/negocio/PortfolioBusiness.java
> +        Optional<Fornecedor> fornecedor = fornecedorRepository.findFornecedorByPessoaIdentificador(dto.getFornecedor().getInformacoes().getIdentificador());
Podemos conversar melhor sobre este ponto? não pude compreender

2023-11-01 00:05 UTC, AydanAmorim commented on src/main/java/br/com/dducl/bffmarketplaceapp/negocio/PortfolioBusiness.java
> +        if (portfolio.isEmpty()) {
Muito bom Isa, eu realmente desconhecia!
o Erik me ajudou a implementar, muito bom mesmo!!

2023-11-01 00:07 UTC, AydanAmorim commented on src/main/java/br/com/dducl/bffmarketplaceapp/negocio/PortfolioBusiness.java
> +        if (fornecedor.isPresent()){
ok - Alterado!

2023-11-01 00:10 UTC, AydanAmorim commented on src/main/java/br/com/dducl/bffmarketplaceapp/negocio/PortfolioBusiness.java
> +        if (portfolioDeletar.isEmpty()){
Done

2023-11-01 00:20 UTC, AydanAmorim commented on src/main/java/br/com/dducl/bffmarketplaceapp/negocio/PortfolioBusiness.java
> +        return "Portfólio deletado com sucesso!";
Done

2023-11-01 00:23 UTC, erickmatheusribeiro approved these changes

2023-11-01 00:47 UTC, AydanAmorim approved these changes

2023-11-01 00:59 UTC, fysabelah approved these changes

2023-11-01 01:00 UTC, merged